apiVersion: apps/v1
kind: Deployment
metadata:
  name: wearapp1
  namespace: default
  labels:
    app: #pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wearapp1
  template:
    metadata:
      labels:
        app: #pyapp
    spec:
      containers:
      - name: pyapp
        image: #spkosana/fastapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  
---
apiVersion: v1
kind: Service
metadata:
  name: #python-service
  namespace: #fastapi
spec:
  selector:
    app: #pyapp
  ports:
  - protocol: "TCP"
    port: 6080
    targetPort: 8000
    nodePort: 31000
  type: LoadBalancer